version: "2"

services:
#
#
#
  nginx:
    image: nginx:alpine
    container_name: ${PROJECT_NAME}_nginx
    volumes_from:
      - php
    volumes:
      - ./_dockerData/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static-data:/static_files
    links:
      - php
      - adminer
    ports:
      - 80:80
#
#
#
  php:
    build: ./_dockerData/php
    image: php:7.1.2-fpm-alpine
    container_name: ${PROJECT_NAME}_php
    working_dir: /var/www/data
    volumes:
      - ./back-end/:/var/www/data
      - ./_dockerData/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - static-data:/var/www/data/storage:z
    entrypoint:
      - php-fpm
    links:
      - mysql
#
#
#
  adminer:
    #build: .
    image: adminer
    container_name: ${PROJECT_NAME}_adminer
    ports:
      - 3307:8080
    links:
      - mysql
    volumes:
      - ./_dockerData/adminer/adminer.css:/var/www/html/adminer.css
#
#
#
  mysql:
    image: mysql
    container_name: ${PROJECT_NAME}_mysql
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD:  somepass
#
#
#
volumes:
  static-data:
  db-data:
#
#
#
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: ${HOST_IP}
